# General settings.
spk: "LINE_3"

# exp tag(for managing experiments)
tag: "test"

sample_rate: 22050

# 1) none 2) tqdm
# NOTE: Jupyterノートブックからrun.shを実行する場合は、none推奨
tqdm: tqdm

# NOTE: benchmarkをtrueにすると、高速化が期待できる分、より多くの
# GPUリソースを必要とする場合があります。
# GPUリソースに余裕がある場合は、true にしてください。
cudnn_benchmark: false
cudnn_deterministic: false

###########################################################
#                DATA PREPARATION SETTING                 #
###########################################################

# PLEASE CHANGE THE PATH BASED ON YOUR ENVIRONMENT
wav_root: "/home/sarulab/eiji_iimori/documents/dataset/dataset/out_JSUT_NICT_LINE/JSUT_NICT_LINE/wav/22050"
lab_root: "/home/sarulab/eiji_iimori/documents/dataset/dataset/out_JSUT_NICT_LINE/textgrid"

n_jobs: 8

train_num: 3200
deveval_num: 640
dev_num: 320
eval_num: 320

###########################################################
#                FEATURE EXTRACTION SETTING               #
###########################################################
filter_length: 1024
hop_length: 256
win_length: 1024
n_mel_channels: 80
mel_fmin: 0
mel_fmax: 8000
clip: 0.00001
log_base: "natural"
pitch_phoneme_averaging: 1
energy_phoneme_averaging: 1
accent_info: 0 
# if ge 1 then lab, else textgrid
###########################################################
#                TRAINING SETTING                         #
###########################################################

acoustic_model: fastspeech2wGMM
vocoder_model: hifigan
# acoustic_modelで利用したいvocoderのconfigやweightへのpathを指定してください.
# 具体的に利用する重みは,vocoder_eval_checkpointになります.
vocoder_config: "conf/train_hifigan/model/hifigan.yaml"
vocoder_weight_base_path: "exp/LINE_3_sr22050_LINE_79_JSUT_NICT_LINE_wo_Teacher_finetuning_FS_GMM_num_gaussians_11/hifigan"

### fastspeech2  ###
# max_train_steps: 200000 → nepochs: 256 s.t. batch_size*group_size = 32, JSUT.
fastspeech2_train_nepochs: 200
fastspeech2_data_batch_size: 8

### hifigan ###
hifigan_train_nepochs: 200
hifigan_data_batch_size: 16

### (optional) Optuna Tuning ###
tuning_config: tuning_fastspeech2wGMM

###########################################################
#                SYNTHESIS SETTING                        #
###########################################################

# リストの逆順で発話を処理する
reverse: false

# 生成する発話の数
# -1 の場合、評価の発話をすべて処理する
# 音声生成にかかる時間を短縮する場合、小さな値（5など）に設定してください
num_eval_utts: -1

acoustic_eval_checkpoint: best_loss.pth
#latest.pth
vocoder_eval_checkpoint: best_loss.pth
#latest.pth
speakers: '{"JSUT": 0, "NICT": 1, "Teacher": 2, "FStudent": 3, "MStudent": 4}'
  NICT: 1 
  Teacher: 2
  FStudent: 3
  MStudent: 4
#speakers: "JSUT","NICT","Teacher","FStudent","MStudent"
