# @package _global_

defaults:
  - model:
  - tuning:

verbose: 100
seed: 773

# 1) none 2) tqdm
tqdm:

cudnn:
  benchmark:
  deterministic:

# Multi-gpu
data_parallel: false

###########################################################
#                DATA SETTING                             #
###########################################################
data:
  # training set
  train:
    utt_list:
    in_dir:
    out_dir:

  # development set
  dev:
    utt_list:
    in_dir:
    out_dir:
  
  acoustic_model:
  emb_dir:
  prosody_emb_dir:
  g_prosody_emb_dir:
  dialogue_info:
  use_hist_num:
  use_prosody_hist_num:
  use_local_prosody_hist_idx:
  use_situation_text:

  # data loader
  num_workers: 5
  batch_size:
  group_size: 4
  accent_info:

###########################################################
#                TRAIN SETTING                            #
###########################################################
train:
  out_dir:
  log_dir:

  # steps can either be specified by steps or epochs
  max_train_steps: -1
  nepochs:
  checkpoint_epoch_interval: 100
  eval_epoch_interval: 50

  vocoder_name:
  vocoder_config:
  vocoder_weight_path:
  sampling_rate:
  mel_scaler_path:
  max_wav_value: 32768.0

  optim:
    optimizer:
      name: Adam
      params:
        lr: 0.0625  # encoder_hidden ** (-0.5)
        betas: [0.9, 0.98]
        eps: 0.000000001
        weight_decay: 0.0
    lr_scheduler:
      _target_: vc_tts_template.fastspeech2.optimizer.ScheduledOptim
      warm_up_step: 2000
      anneal_steps: [150000, 200000, 250000]
      anneal_rate: 0.3
      max_lr_scale: 0.016  # max_lr = 0.001 / base_lr = 0.0625 
  
  criterion:
    _target_: vc_tts_template.fastspeech2wContexts.fastspeech2wContextswPEProsodywCurrentMel.FastSpeech2wContextswPEProsodywCurrentMelsLoss
    # _target_: vc_tts_template.fastspeech2wContexts.fastspeech2wContextswPEProsodyAfterwoPEPCE.FastSpeech2wContextswPEProsodyAfterwoPEPCEsLoss
    # _target_: vc_tts_template.fastspeech2.loss.FastSpeech2Loss
    pitch_feature_level:
    energy_feature_level:
    beta: 0.01
    # g_beta: 0.02

  pretrained:
    # 注意: ./run.shのいるディレクトリがcwdです.
    # 例: "exp/jsut_sr22050/fastspeech2/latest.pth"
    # checkpoint: exp/LINE_wContextwPEProsody_4_sr22050_LINE_wContextwPEProsody_74_CL_stage1/fastspeech2wPEProsodywoPEPCE/latest.pth
    # checkpoint: exp/LINE_wContextwPEProsody_7_sr22050_LINE_wContextwPEProsody_97_CL_stage1_seg/fastspeech2wPEProsodywoPEPCE/latest_wClonePE.pth
    checkpoint: 
    #../fastspeech2/exp/jsut_sr22050_JSUT_5/fastspeech2/latest.pth
    # checkpoint: exp/LINE_wContextwPEProsody_8_sr22050_LINE_wContextwPEProsody_101_CL_stage1/fastspeech2wPEProsodywoPEPCE/latest.pth
    # checkpoint: exp/LINE_wContextwPEProsody_9_sr22050_LINE_wContextwPEProsody_102_CL_stage1_seg/fastspeech2wPEProsodywoPEPCE/latest.pth
    optimizer_reset: True
    load_modules:
